name: Elixir CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    env:
      ADVIZER_SERAPHIN_API_KEY: ${{ secrets.ADVIZER_SERAPHIN_API_KEY }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
        with:
          elixir-version: '1.12.3'
          otp-version: '24.1'

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Install dependencies
        run: mix deps.get

      - name: Check retired dependencies
        run: mix hex.audit

      - name: Check unused dependencies
        run: mix deps.unlock --check-unused

      - name: Check for vulnerabilities
        run: mix deps.audit

      - name: Check formatting
        run: mix format --dry-run --check-formatted

      - name: Compilation
        run: mix compile --all-warnings --warning-as-errors

      - name: Check Migrations Consistency
        run: mix ecto.create && mix ecto.migrate && mix ecto.rollback --all

      - name: Check Security Issues
        run: mix sobelow

      - name: Run tests
        run: mix test